@startuml
actor User
actor Database
rectangle {
User -> (View character)
User -> (Save character)
User -> (Create Class/Race/Alignment)
(Create Class/Race/Alignment) .> (Edit character information):uses
User -> (Edit character information)

Database -up-> (Display Character)
Database -up-> (Save character)
}
@enduml